-- Wave A3: Database indexes. Rollback: DROP INDEX IF EXISTS idx_wave_a_* names.
DO $$ BEGIN IF to_regclass('orders') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='status') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_orders_status ON orders(status)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('orders') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='customer_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_orders_customer_id ON orders(customer_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('orders') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='vendor_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_orders_vendor_id ON orders(vendor_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('orders') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='driver_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_orders_driver_id ON orders(driver_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('orders') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='created_at') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_orders_created_at ON orders(created_at)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('orders') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='payment_status') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_orders_payment_status ON orders(payment_status)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('order_events') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='order_events' AND column_name='order_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_order_events_order_id ON order_events(order_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('order_events') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='order_events' AND column_name='created_at') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_order_events_created_at ON order_events(created_at)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('notifications') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notifications' AND column_name='user_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_notifications_user_id ON notifications(user_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('notifications') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notifications' AND column_name='read') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_notifications_read ON notifications(read)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('driver_location_history') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='driver_location_history' AND column_name='driver_id') AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='driver_location_history' AND column_name='captured_at') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_driver_location_history_driver_id_captured_at ON driver_location_history(driver_id, captured_at)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('quotes') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quotes' AND column_name='customer_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_quotes_customer_id ON quotes(customer_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('quotes') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quotes' AND column_name='session_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_quotes_session_id ON quotes(session_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('quotes') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quotes' AND column_name='created_at') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_quotes_created_at ON quotes(created_at)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('payment_transactions') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payment_transactions' AND column_name='order_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_payment_transactions_order_id ON payment_transactions(order_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('payment_transactions') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payment_transactions' AND column_name='stripe_payment_intent_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_payment_transactions_stripe_payment_intent_id ON payment_transactions(stripe_payment_intent_id)'; END IF; END $$;
DO $$ BEGIN IF to_regclass('addresses') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='addresses' AND column_name='user_id') THEN EXECUTE 'CREATE INDEX IF NOT EXISTS idx_wave_a_addresses_user_id ON addresses(user_id)'; END IF; END $$;
